#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jul 27 20:14:46 KST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Sildur's Vibrant Shaders v2.01 Extreme.zip
